//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHTW.CodeRunner.DataAccess.Sql.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FHTW.CodeRunner.DataAccess.Sql.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {   // Collection 1, English, German, C++, C#, V1, V2, V3
        ///        &quot;Title&quot;: &quot;Title_1&quot;,
        ///        &quot;Created&quot;: &quot;2020-08-23T18:25:43.51&quot;,
        ///        &quot;FkUserId&quot;: 1
        ///    }
        ///].
        /// </summary>
        internal static string collection {
            get {
                return ResourceManager.GetString("collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  { // Collection 1, Exercise 1, English, C++
        ///    &quot;FkCollectionId&quot;: 1,
        ///    &quot;VersionNumber&quot;: 1,
        ///    &quot;FkExerciseId&quot;: 1,
        ///    &quot;FkProgrammingLanguageId&quot;: 1,
        ///    &quot;FkWrittenLanguageId&quot;: 1
        ///  },
        ///  { // Collection 1, Exercise 2, English, C++
        ///    &quot;FkCollectionId&quot;: 1,
        ///    &quot;VersionNumber&quot;: 1,
        ///    &quot;FkExerciseId&quot;: 2,
        ///    &quot;FkProgrammingLanguageId&quot;: 6,
        ///    &quot;FkWrittenLanguageId&quot;: 1
        ///  }
        ///].
        /// </summary>
        internal static string collection_exercise {
            get {
                return ResourceManager.GetString("collection_exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {   // Collection 1, English, C++
        ///        &quot;FullTitle&quot;: &quot;FullTitle_1&quot;,
        ///        &quot;ShortTitle&quot;: &quot;ShortTitle_1&quot;,
        ///        &quot;Introduction&quot;: &quot;Introduction_1&quot;,
        ///        &quot;FkCollectionId&quot;: 1,
        ///        &quot;FkWrittenLanguageId&quot;: 1
        ///    }
        ///].
        /// </summary>
        internal static string collection_language {
            get {
                return ResourceManager.GetString("collection_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;Message&quot;: &quot;Message_1&quot;,
        ///        &quot;Created&quot;: &quot;2013-05-23T18:28:43.51&quot;,
        ///        &quot;FkExerciseId&quot;: 1,
        ///        &quot;FkUserId&quot;: 1
        ///    },
        ///    {
        ///        &quot;Message&quot;: &quot;Message_2&quot;,
        ///        &quot;Created&quot;: &quot;2012-05-23T18:28:43.51&quot;,
        ///        &quot;FkExerciseId&quot;: 1,
        ///        &quot;FkUserId&quot;: 2
        ///    },
        ///    {
        ///        &quot;Message&quot;: &quot;Message_3&quot;,
        ///        &quot;Created&quot;: &quot;2018-05-23T18:28:43.51&quot;,
        ///        &quot;FkExerciseId&quot;: 1,
        ///        &quot;FkUserId&quot;: 4
        ///    },
        ///    {
        ///        &quot;Message&quot;: &quot;Message_4&quot;,
        ///        &quot;Created&quot;: &quot;2019-05-23T18: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;Number&quot;: 2,
        ///        &quot;FkExerciseId&quot;: 1,
        ///        &quot;FkUserId&quot;: 2
        ///    },
        ///    {
        ///        &quot;Number&quot;: 4,
        ///        &quot;FkExerciseId&quot;: 1,
        ///        &quot;FkUserId&quot;: 3
        ///    },
        ///    {
        ///        &quot;Number&quot;: 1,
        ///        &quot;FkExerciseId&quot;: 1,
        ///        &quot;FkUserId&quot;: 4
        ///    },
        ///    {
        ///        &quot;Number&quot;: 5,
        ///        &quot;FkExerciseId&quot;: 2,
        ///        &quot;FkUserId&quot;: 1
        ///    }
        ///].
        /// </summary>
        internal static string difficulty {
            get {
                return ResourceManager.GetString("difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {   // Exercise 1, English, German, C++, C#, V1, V2, V3
        ///        &quot;Title&quot;: &quot;Title_1&quot;,
        ///        &quot;Created&quot;: &quot;2020-04-23T18:25:43.51&quot;,
        ///        &quot;FkUserId&quot;: 1
        ///    },
        ///    {   // Exercise 2, English, German, Python, Java, V1
        ///        &quot;Title&quot;: &quot;Title_2&quot;,
        ///        &quot;Created&quot;: &quot;2019-06-13T17:15:33.34&quot;,
        ///        &quot;FkUserId&quot;: 1
        ///    },
        ///    {   // Exercise 3, German, C, V1
        ///        &quot;Title&quot;: &quot;Title_3&quot;,
        ///        &quot;Created&quot;: &quot;2018-11-27T10:22:46.51&quot;,
        ///        &quot;FkUserId&quot;: 3
        ///    }
        ///].
        /// </summary>
        internal static string exercise {
            get {
                return ResourceManager.GetString("exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {   // Exercise 1, English, C++, V1
        ///        &quot;FkProgrammingLanguageId&quot;: 1,
        ///        &quot;Description&quot;: &quot;Description_c++_V1&quot;,
        ///        &quot;Hint&quot;: &quot;Hint_c++_V1&quot;,
        ///        &quot;FkExerciseLanguageId&quot;: 1,
        ///        &quot;FkTestSuiteId&quot;: 1,
        ///        &quot;FieldLines&quot;: 18,
        ///        &quot;GradingFlag&quot;: true,
        ///        &quot;SubtractSystem&quot;: &quot;10, 20, ..._c++_V1&quot;,
        ///        &quot;ObtainablePoints&quot;: 10,
        ///        &quot;IdNum&quot;: 123,
        ///        &quot;Solution&quot;: &quot;n_Solution_c++_V1&quot;,
        ///        &quot;Prefill&quot;: &quot;n_Prefill_c++_V1&quot;,
        ///        &quot;Feedback&quot;: &quot;Feedback_c++_V1&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string exercise_body {
            get {
                return ResourceManager.GetString("exercise_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {   // Exercise 1, English, V1
        ///        &quot;FullTitle&quot;: &quot;Full_Title_1_V1&quot;,
        ///        &quot;Introduction&quot;: &quot;Introduction_1_V1&quot;,
        ///        &quot;FkUserId&quot;: 1,
        ///        &quot;TemplateParam&quot;: &quot;template_param_1_V1&quot;,
        ///        &quot;TemplateParamLiftFlag&quot;: false,
        ///        &quot;TwigAllFlag&quot;: true
        ///    },
        ///    {   // Exercise 1, German, V1
        ///        &quot;FullTitle&quot;: &quot;Voller_Titel_1_V1&quot;,
        ///        &quot;Introduction&quot;: &quot;Einleitung_1_V1&quot;,
        ///        &quot;FkUserId&quot;: 1,
        ///        &quot;TemplateParam&quot;: &quot;template_param_1_V1&quot;,
        ///        &quot;TemplateParamLiftFlag&quot;: false,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string exercise_header {
            get {
                return ResourceManager.GetString("exercise_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {   // Exercise 1, English, V1
        ///        &quot;FkWrittenLanguageId&quot;: 1,
        ///        &quot;FkExerciseVersionId&quot;: 1,
        ///        &quot;FkExerciseHeaderId&quot;: 1
        ///    },
        ///    {   // Exercise 1, German, V1
        ///        &quot;FkWrittenLanguageId&quot;: 2,
        ///        &quot;FkExerciseVersionId&quot;: 1,
        ///        &quot;FkExerciseHeaderId&quot;: 2
        ///    },
        ///    {   // Exercise 1, English, V2
        ///        &quot;FkWrittenLanguageId&quot;: 1,
        ///        &quot;FkExerciseVersionId&quot;: 2,
        ///        &quot;FkExerciseHeaderId&quot;: 3
        ///    },
        ///    {   // Exercise 1, German, V2
        ///        &quot;FkWrittenLanguageId&quot;: 2,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string exercise_language {
            get {
                return ResourceManager.GetString("exercise_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;FkTagId&quot;: 1,
        ///        &quot;FkExerciseId&quot;: 1
        ///    },
        ///    {
        ///        &quot;FkTagId&quot;: 2,
        ///        &quot;FkExerciseId&quot;: 1
        ///    },
        ///    {
        ///        &quot;FkTagId&quot;: 3,
        ///        &quot;FkExerciseId&quot;: 1
        ///    },
        ///    {
        ///        &quot;FkTagId&quot;: 2,
        ///        &quot;FkExerciseId&quot;: 2
        ///    },
        ///    {
        ///        &quot;FkTagId&quot;: 4,
        ///        &quot;FkExerciseId&quot;: 1
        ///    },
        ///    {
        ///        &quot;FkTagId&quot;: 5,
        ///        &quot;FkExerciseId&quot;: 1
        ///    },
        ///    {
        ///        &quot;FkTagId&quot;: 5,
        ///        &quot;FkExerciseId&quot;: 2
        ///    },
        ///    {
        ///        &quot;FkTagId&quot;: 6,
        ///        &quot;FkExerciseId&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string exercise_tag {
            get {
                return ResourceManager.GetString("exercise_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {   // Exercise 1, V1
        ///        &quot;VersionNumber&quot;: 1,
        ///        &quot;CreatorRating&quot;: 3,
        ///        &quot;CreatorDifficulty&quot;: 4,
        ///        &quot;LastModified&quot;: &quot;2020-04-23T18:28:43.51&quot;,
        ///        &quot;ValidState&quot;: 1,
        ///        &quot;FkUserId&quot;: 1,
        ///        &quot;FkExerciseId&quot;: 1
        ///    },
        ///    {   // Exercise 1, V2
        ///        &quot;VersionNumber&quot;: 2,
        ///        &quot;CreatorRating&quot;: 4,
        ///        &quot;CreatorDifficulty&quot;: 5,
        ///        &quot;LastModified&quot;: &quot;2020-05-14T18:28:43.51&quot;,
        ///        &quot;ValidState&quot;: 1,
        ///        &quot;FkUserId&quot;: 1,
        ///        &quot;FkExerciseId&quot;: 1
        ///    },
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string exercise_version {
            get {
                return ResourceManager.GetString("exercise_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;Name&quot;: &quot;C++&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;C#&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;Java&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;Rust&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;C&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;Python&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;JavaScript&quot;
        ///    }
        ///].
        /// </summary>
        internal static string programming_language {
            get {
                return ResourceManager.GetString("programming_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;Name&quot;: &quot;c++_question_type&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;c#_question_type&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;python_question_type&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;java_question_type&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;c_question_type&quot;
        ///    }
        ///].
        /// </summary>
        internal static string questiontype {
            get {
                return ResourceManager.GetString("questiontype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;Number&quot;: 4,
        ///        &quot;FkExerciseId&quot;: 1,
        ///        &quot;FkUserId&quot;: 2
        ///    },
        ///    {
        ///        &quot;Number&quot;: 5,
        ///        &quot;FkExerciseId&quot;: 1,
        ///        &quot;FkUserId&quot;: 3
        ///    },
        ///    {
        ///        &quot;Number&quot;: 3,
        ///        &quot;FkExerciseId&quot;: 1,
        ///        &quot;FkUserId&quot;: 4
        ///    },
        ///    {
        ///        &quot;Number&quot;: 1,
        ///        &quot;FkExerciseId&quot;: 2,
        ///        &quot;FkUserId&quot;: 1
        ///    }
        ///].
        /// </summary>
        internal static string rating {
            get {
                return ResourceManager.GetString("rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;Name&quot;: &quot;algorithms&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;unit tests&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;tree&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;linked list&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;ml&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;oop&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;game&quot;
        ///    }
        ///].
        /// </summary>
        internal static string tag {
            get {
                return ResourceManager.GetString("tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {   // Exercise 1, Testcase 1, C++, V1
        ///        &quot;OrderUsed&quot;: 1,
        ///        &quot;TestCode&quot;: &quot;test_code_1_c++_V1&quot;,
        ///        &quot;StandardInput&quot;: &quot;standard_input_1_c++_V1&quot;,
        ///        &quot;ExpectedOutput&quot;: &quot;expected_output_1_c++_V1&quot;,
        ///        &quot;AdditionalData&quot;: &quot;additional_data_1_c++_V1&quot;,
        ///        &quot;Points&quot;: 2,
        ///        &quot;FkTestSuiteId&quot;: 1,
        ///        &quot;UseAsExampleFlag&quot;: false,
        ///        &quot;HideOnFailFlag&quot;: true,
        ///        &quot;DisplayType&quot;: &quot;HIDE&quot;
        ///    },
        ///    {   // Exercise 1, Testcase 2, C++, V1
        ///        &quot;OrderUsed&quot;: 2,
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testcase {
            get {
                return ResourceManager.GetString("testcase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {   // Exercise 1, C++, V1
        ///        &quot;FkQuestionTypeId&quot;: 1,
        ///        &quot;TemplateDebugFlag&quot;: true,
        ///        &quot;TestOnSaveFlag&quot;: false,
        ///        &quot;GlobalExtraParam&quot;: &quot;global_extra_param_c++_V1&quot;,
        ///        &quot;RuntimeData&quot;: &quot;runtime_data_c++_V1&quot;,
        ///        &quot;PreCheck&quot;: 0,
        ///        &quot;GeneralFeedbackDisplay&quot;: 1
        ///    },
        ///    {   // Exercise 1, C#, V1
        ///        &quot;FkQuestionTypeId&quot;: 2,
        ///        &quot;TemplateDebugFlag&quot;: true,
        ///        &quot;TestOnSaveFlag&quot;: false,
        ///        &quot;GlobalExtraParam&quot;: &quot;global_extra_param_c#_V1&quot;,
        ///        &quot;Ru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testsuite {
            get {
                return ResourceManager.GetString("testsuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;Name&quot;: &quot;fhtw&quot;,
        ///        &quot;Password&quot;: &quot;1a998df5fcdda7a891b54846dd8377df64286d3244c17e47dfb37c8d39d4a6469942367715e5c72cf98c0054cb2eb42238cd42b6d46f36fe65d34d7d5a133f95&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;sabrina&quot;,
        ///        &quot;Password&quot;: &quot;3544e2e8cdfc2c8d1bb44ab4e80679d0d9cabaa57c5de30500a763e72382242f750027fd553913013f41b113594010a57d990e8a989c098d1e4e45af9b13ad15&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;michi&quot;,
        ///      &quot;Password&quot;: &quot;05da9778da007b171a01250742119aa8b5116afbdc1539df9f28f97cbe1bfe8252dfd26b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;Name&quot;: &quot;English&quot;
        ///    },
        ///    {
        ///        &quot;Name&quot;: &quot;German&quot;
        ///    }
        ///].
        /// </summary>
        internal static string written_language {
            get {
                return ResourceManager.GetString("written_language", resourceCulture);
            }
        }
    }
}
