version: '3.1'

# docker-compose up (build and start db)
# docker-compose start (start db)
# docker-compose stop (stop db)

services:

  db:
    image: postgres:13
    container_name: postgresql-container-local
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: coderunnerdb
    ports: 
        - 5432:5432 