version: '3.4'

services:
  fhtw.coderunner.services:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=jDyhoAhAY6mfGa189lSB
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/dev-key.pfx
    ports:
      - 5000:80
      - 5001:443
