version: '3.4'

services:
  fhtw.coderunner.services:
    image: ${DOCKER_REGISTRY-}fhtwcoderunnerservices
    build:
      context: .
      dockerfile: FHTW.CodeRunner.Services/Dockerfile
    links:
        - "db"
