version: '3.4'

services:
  db:
    image: postgres:13
    container_name: postgresql-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: coderunnerdb
    ports: 
        - 5432:5432 
    volumes: 
      - ./init:/docker-entrypoint-initdb.d
  fhtw.coderunner.services:
    image: ${DOCKER_REGISTRY-}fhtwcoderunnerservices
    build:
      context: .
      dockerfile: FHTW.CodeRunner.Services/Dockerfile
    links:
        - "db"